corrected my own sentences
Hacker0x01/pingpong pull request #13
Opened 2017-05-10 12:34 UTC by ivdma

2017-05-10 12:35 UTC, Willianvdv submitted a review, later dismissed

2017-05-10 12:35 UTC, Willianvdv commented on README.md
> +Diversity at HackerOne is a hot topic. We aim to be as diverse as possible. Not only when working on world-class product, but also during teambuilding. Therefore any diverse playing member (women, fo
- last comma can be removed
- `on world-class` should be `on a world-class`

2017-05-10 12:36 UTC, Willianvdv commented
@spidfire you like?

2017-05-10 12:39 UTC, spidfire commented
Will Frisian and Brabandic players get no points or more?
Is it not better to give new players 1 point instead of these specific groups?

2017-05-10 12:45 UTC, ivdma commented
@spidfire Frisian and Brabantic players are, sadly enough, mostly being referred to as 'foreigners', which is unfair. So to prevent the confusion we exclude those groups from being awarded with 1 life at the beginning of the round and only award really diverse players like me with it. That, hopefully, will attract more diverse people to @Hacker0x01 company.

2017-05-10 12:45 UTC, Willianvdv commented
@spidfire excellent feedback, let's give all inexperienced players a beginners life. The big question, when do you become an experienced player?

2017-05-10 12:48 UTC, ivdma commented
@Willianvdv @spidfire beating @mvgijssel for the first time could draw that line.

2017-05-10 15:00 UTC, mvgijssel commented
After playing around with this rule, is it an idea to lose the life before the final starts? In which case you also have to call "reset" if you make it? That way it's a little bit more fair towards the regular players.

2017-05-10 15:07 UTC, ivdma commented
My suggestion: 
```ruby
# At the beginning of any round
if lives.count == 0
  lives += Life.new
# else
#   No new life 
end
```

2017-05-10 15:37 UTC, Willianvdv commented
Can't we refactor this whole README into code? way easier

2017-05-10 15:38 UTC, Willianvdv requested changes

2017-05-10 15:38 UTC, Willianvdv commented on README.md
> +Diversity at HackerOne is a hot topic. We aim to be as diverse as possible. Not only when working on a world-class product, but also during teambuilding. Therefore any diverse playing member (women,
remove the exclusions, everyone can have a beginners life 🥇

2017-05-11 10:05 UTC, ivdma commented on README.md
> +Diversity at HackerOne is a hot topic. We aim to be as diverse as possible. Not only when working on a world-class product, but also during teambuilding. Therefore any diverse playing member (women,
So basically it's not about diversity anymore but about the level of the player. But then how do you decide what level the player has reached?

2017-05-11 10:13 UTC, RSO commented on README.md
> +Diversity at HackerOne is a hot topic. We aim to be as diverse as possible. Not only when working on a world-class product, but also during teambuilding. Therefore any diverse playing member (women,
In comes reputation! I would suggest we add +7 points in the overall scoring for won matches, -5 for pulling a jeurissen, etc. @mvgijssel probably has some super strong opinions on what gem to use to implement reputation.

2017-05-15 09:26 UTC, esjee commented on README.md
> +Diversity at HackerOne is a hot topic. We aim to be as diverse as possible. Not only when working on a world-class product, but also during teambuilding. Therefore any diverse playing member (women,
Sink or swim. You get it for 5 days, it's your responsibility to shape up during that time.

2017-05-15 10:26 UTC, spidfire commented
Just wondering do you only get visitors from the SF office or also from one of your new offices?

2017-05-15 10:39 UTC, ivdma commented
This information will remain undisclosed.

2017-05-15 12:17 UTC, Willianvdv approved these changes

2017-05-15 12:18 UTC, Willianvdv commented on README.md
> +  lives << Live.new(type: :beginner) if lives.count == 1
```ruby
irb(main):001:0> 1.count
NoMethodError: undefined method `count' for 1:Fixnum
	from (irb):1
	from /Users/willian/.rbenv/versions/2.3.3/bin/irb:11:in `<main>'
```

2017-05-15 12:19 UTC, merged