Stashing 1.1
Hacker0x01/pingpong pull request #16
Opened 2018-01-10 09:54 UTC by ivdma

Lot's of stashing happens nowadays...

2018-01-10 12:10 UTC, martijnrusschen requested changes

2018-01-10 12:10 UTC, martijnrusschen commented on README.md
> +Player is allowed to grab and stash any amount of PingPong balls in their hand. Player shamefully loses one life when caught stashing PingPong balls in pockets or hands.
any amount  -> More than one

2018-01-10 14:43 UTC, ivdma commented
I'd rather remove any specification of it

2018-01-10 14:46 UTC, martijnrusschen commented
> Player is allowed to grab and stash PingPong balls in their hand. Player shamefully loses one life when caught stashing PingPong balls in pockets or hands.

The first sentence says you can grab balls in your hand, but the second sentence says you can't stash. Whut?

2018-01-26 14:16 UTC, martijnrusschen commented
why not?

2018-01-26 14:19 UTC, Willianvdv commented
@miraymazlumoglu where did you hide them?

2018-01-26 14:19 UTC, miraymazlumoglu commented
You will never know

2018-01-26 14:20 UTC, miraymazlumoglu commented
I will never show

2018-01-26 14:51 UTC, ivdma commented
> You will never know
> 
> I will never show

That is why guilty person shamefully loses their life!

2018-02-21 15:39 UTC, ivdma commented
🍃 🚢

2018-02-21 15:39 UTC, closed without merging